/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpdatePasswordRouteImport } from './routes/update-password'
import { Route as RegisterSuccessRouteImport } from './routes/register-success'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as SandboxRegistryRouteImport } from './routes/sandbox/registry'
import { Route as SandboxExplorerRouteImport } from './routes/sandbox/explorer'
import { Route as AuthOauthRouteImport } from './routes/auth/oauth'
import { Route as AuthErrorRouteImport } from './routes/auth/error'
import { Route as AuthConfirmRouteImport } from './routes/auth/confirm'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as ProtectedProfileRouteImport } from './routes/_protected/profile'
import { Route as ProtectedWordsIndexRouteImport } from './routes/_protected/words/index'
import { Route as ProtectedStudyIndexRouteImport } from './routes/_protected/study/index'
import { Route as ProtectedReadIndexRouteImport } from './routes/_protected/read/index'
import { Route as ProtectedDocumentsIndexRouteImport } from './routes/_protected/documents/index'
import { Route as ProtectedWordsIdRouteImport } from './routes/_protected/words/$id'
import { Route as ProtectedStudySessionRouteImport } from './routes/_protected/study/session'
import { Route as ProtectedReadIdRouteImport } from './routes/_protected/read/$id'
import { Route as ProtectedDocumentsIdRouteImport } from './routes/_protected/documents/$id'

const UpdatePasswordRoute = UpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterSuccessRoute = RegisterSuccessRouteImport.update({
  id: '/register-success',
  path: '/register-success',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const SandboxRegistryRoute = SandboxRegistryRouteImport.update({
  id: '/sandbox/registry',
  path: '/sandbox/registry',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxExplorerRoute = SandboxExplorerRouteImport.update({
  id: '/sandbox/explorer',
  path: '/sandbox/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOauthRoute = AuthOauthRouteImport.update({
  id: '/auth/oauth',
  path: '/auth/oauth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedProfileRoute = ProtectedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedWordsIndexRoute = ProtectedWordsIndexRouteImport.update({
  id: '/words/',
  path: '/words/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedStudyIndexRoute = ProtectedStudyIndexRouteImport.update({
  id: '/study/',
  path: '/study/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedReadIndexRoute = ProtectedReadIndexRouteImport.update({
  id: '/read/',
  path: '/read/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDocumentsIndexRoute = ProtectedDocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedWordsIdRoute = ProtectedWordsIdRouteImport.update({
  id: '/words/$id',
  path: '/words/$id',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedStudySessionRoute = ProtectedStudySessionRouteImport.update({
  id: '/study/session',
  path: '/study/session',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedReadIdRoute = ProtectedReadIdRouteImport.update({
  id: '/read/$id',
  path: '/read/$id',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDocumentsIdRoute = ProtectedDocumentsIdRouteImport.update({
  id: '/documents/$id',
  path: '/documents/$id',
  getParentRoute: () => ProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/register-success': typeof RegisterSuccessRoute
  '/update-password': typeof UpdatePasswordRoute
  '/profile': typeof ProtectedProfileRoute
  '/settings': typeof ProtectedSettingsRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/oauth': typeof AuthOauthRoute
  '/sandbox/explorer': typeof SandboxExplorerRoute
  '/sandbox/registry': typeof SandboxRegistryRoute
  '/documents/$id': typeof ProtectedDocumentsIdRoute
  '/read/$id': typeof ProtectedReadIdRoute
  '/study/session': typeof ProtectedStudySessionRoute
  '/words/$id': typeof ProtectedWordsIdRoute
  '/documents/': typeof ProtectedDocumentsIndexRoute
  '/read/': typeof ProtectedReadIndexRoute
  '/study/': typeof ProtectedStudyIndexRoute
  '/words/': typeof ProtectedWordsIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/register-success': typeof RegisterSuccessRoute
  '/update-password': typeof UpdatePasswordRoute
  '/profile': typeof ProtectedProfileRoute
  '/settings': typeof ProtectedSettingsRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/oauth': typeof AuthOauthRoute
  '/sandbox/explorer': typeof SandboxExplorerRoute
  '/sandbox/registry': typeof SandboxRegistryRoute
  '/': typeof ProtectedIndexRoute
  '/documents/$id': typeof ProtectedDocumentsIdRoute
  '/read/$id': typeof ProtectedReadIdRoute
  '/study/session': typeof ProtectedStudySessionRoute
  '/words/$id': typeof ProtectedWordsIdRoute
  '/documents': typeof ProtectedDocumentsIndexRoute
  '/read': typeof ProtectedReadIndexRoute
  '/study': typeof ProtectedStudyIndexRoute
  '/words': typeof ProtectedWordsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/register-success': typeof RegisterSuccessRoute
  '/update-password': typeof UpdatePasswordRoute
  '/_protected/profile': typeof ProtectedProfileRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/oauth': typeof AuthOauthRoute
  '/sandbox/explorer': typeof SandboxExplorerRoute
  '/sandbox/registry': typeof SandboxRegistryRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/documents/$id': typeof ProtectedDocumentsIdRoute
  '/_protected/read/$id': typeof ProtectedReadIdRoute
  '/_protected/study/session': typeof ProtectedStudySessionRoute
  '/_protected/words/$id': typeof ProtectedWordsIdRoute
  '/_protected/documents/': typeof ProtectedDocumentsIndexRoute
  '/_protected/read/': typeof ProtectedReadIndexRoute
  '/_protected/study/': typeof ProtectedStudyIndexRoute
  '/_protected/words/': typeof ProtectedWordsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/register-success'
    | '/update-password'
    | '/profile'
    | '/settings'
    | '/auth/confirm'
    | '/auth/error'
    | '/auth/oauth'
    | '/sandbox/explorer'
    | '/sandbox/registry'
    | '/documents/$id'
    | '/read/$id'
    | '/study/session'
    | '/words/$id'
    | '/documents/'
    | '/read/'
    | '/study/'
    | '/words/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/register-success'
    | '/update-password'
    | '/profile'
    | '/settings'
    | '/auth/confirm'
    | '/auth/error'
    | '/auth/oauth'
    | '/sandbox/explorer'
    | '/sandbox/registry'
    | '/'
    | '/documents/$id'
    | '/read/$id'
    | '/study/session'
    | '/words/$id'
    | '/documents'
    | '/read'
    | '/study'
    | '/words'
  id:
    | '__root__'
    | '/_protected'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/register-success'
    | '/update-password'
    | '/_protected/profile'
    | '/_protected/settings'
    | '/auth/confirm'
    | '/auth/error'
    | '/auth/oauth'
    | '/sandbox/explorer'
    | '/sandbox/registry'
    | '/_protected/'
    | '/_protected/documents/$id'
    | '/_protected/read/$id'
    | '/_protected/study/session'
    | '/_protected/words/$id'
    | '/_protected/documents/'
    | '/_protected/read/'
    | '/_protected/study/'
    | '/_protected/words/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  RegisterRoute: typeof RegisterRoute
  RegisterSuccessRoute: typeof RegisterSuccessRoute
  UpdatePasswordRoute: typeof UpdatePasswordRoute
  AuthConfirmRoute: typeof AuthConfirmRoute
  AuthErrorRoute: typeof AuthErrorRoute
  AuthOauthRoute: typeof AuthOauthRoute
  SandboxExplorerRoute: typeof SandboxExplorerRoute
  SandboxRegistryRoute: typeof SandboxRegistryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/update-password': {
      id: '/update-password'
      path: '/update-password'
      fullPath: '/update-password'
      preLoaderRoute: typeof UpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-success': {
      id: '/register-success'
      path: '/register-success'
      fullPath: '/register-success'
      preLoaderRoute: typeof RegisterSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/sandbox/registry': {
      id: '/sandbox/registry'
      path: '/sandbox/registry'
      fullPath: '/sandbox/registry'
      preLoaderRoute: typeof SandboxRegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandbox/explorer': {
      id: '/sandbox/explorer'
      path: '/sandbox/explorer'
      fullPath: '/sandbox/explorer'
      preLoaderRoute: typeof SandboxExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/oauth': {
      id: '/auth/oauth'
      path: '/auth/oauth'
      fullPath: '/auth/oauth'
      preLoaderRoute: typeof AuthOauthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/profile': {
      id: '/_protected/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProtectedProfileRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/words/': {
      id: '/_protected/words/'
      path: '/words'
      fullPath: '/words/'
      preLoaderRoute: typeof ProtectedWordsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/study/': {
      id: '/_protected/study/'
      path: '/study'
      fullPath: '/study/'
      preLoaderRoute: typeof ProtectedStudyIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/read/': {
      id: '/_protected/read/'
      path: '/read'
      fullPath: '/read/'
      preLoaderRoute: typeof ProtectedReadIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/documents/': {
      id: '/_protected/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof ProtectedDocumentsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/words/$id': {
      id: '/_protected/words/$id'
      path: '/words/$id'
      fullPath: '/words/$id'
      preLoaderRoute: typeof ProtectedWordsIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/study/session': {
      id: '/_protected/study/session'
      path: '/study/session'
      fullPath: '/study/session'
      preLoaderRoute: typeof ProtectedStudySessionRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/read/$id': {
      id: '/_protected/read/$id'
      path: '/read/$id'
      fullPath: '/read/$id'
      preLoaderRoute: typeof ProtectedReadIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/documents/$id': {
      id: '/_protected/documents/$id'
      path: '/documents/$id'
      fullPath: '/documents/$id'
      preLoaderRoute: typeof ProtectedDocumentsIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedProfileRoute: typeof ProtectedProfileRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedDocumentsIdRoute: typeof ProtectedDocumentsIdRoute
  ProtectedReadIdRoute: typeof ProtectedReadIdRoute
  ProtectedStudySessionRoute: typeof ProtectedStudySessionRoute
  ProtectedWordsIdRoute: typeof ProtectedWordsIdRoute
  ProtectedDocumentsIndexRoute: typeof ProtectedDocumentsIndexRoute
  ProtectedReadIndexRoute: typeof ProtectedReadIndexRoute
  ProtectedStudyIndexRoute: typeof ProtectedStudyIndexRoute
  ProtectedWordsIndexRoute: typeof ProtectedWordsIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedProfileRoute: ProtectedProfileRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedDocumentsIdRoute: ProtectedDocumentsIdRoute,
  ProtectedReadIdRoute: ProtectedReadIdRoute,
  ProtectedStudySessionRoute: ProtectedStudySessionRoute,
  ProtectedWordsIdRoute: ProtectedWordsIdRoute,
  ProtectedDocumentsIndexRoute: ProtectedDocumentsIndexRoute,
  ProtectedReadIndexRoute: ProtectedReadIndexRoute,
  ProtectedStudyIndexRoute: ProtectedStudyIndexRoute,
  ProtectedWordsIndexRoute: ProtectedWordsIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRoute,
  RegisterSuccessRoute: RegisterSuccessRoute,
  UpdatePasswordRoute: UpdatePasswordRoute,
  AuthConfirmRoute: AuthConfirmRoute,
  AuthErrorRoute: AuthErrorRoute,
  AuthOauthRoute: AuthOauthRoute,
  SandboxExplorerRoute: SandboxExplorerRoute,
  SandboxRegistryRoute: SandboxRegistryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
